version: '3.8'

services:

  server:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://vickie:newpassword@db/todo
      - "TEST_DATABASE_URL=sqlite+aiosqlite:///:memory:"
    ports:
      - "5000:5000"
    restart: always
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=vickie
      - POSTGRES_PASSWORD=newpassword
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: